#!/usr/bin/env python3
"""Aggregate the architecture-sweep per-run artifacts into presentation outputs.

Reads each ``runs/sweep-arch/<basis>/`` directory written by
``sweep_astronaut.sh`` (config.json + loss.csv + recon_final.png) and produces:

- ``examples/data/architecture_sweep/results.csv``
- ``examples/data/architecture_sweep/comparison_grid.png``
- ``examples/data/architecture_sweep/loss_curves.svg``

The markdown writeup is hand-curated in ``architecture_sweep.md`` and references
this directory's artifacts. The numeric pieces of the writeup's results table
can be regenerated by re-running this script.
"""

from __future__ import annotations

import csv
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


REPO_ROOT = Path(__file__).resolve().parent.parent
RUN_DIR = REPO_ROOT / "runs" / "sweep-arch"
OUT_DIR = REPO_ROOT / "examples" / "data" / "architecture_sweep"

BASES = [
    "siren",
    "hsiren",
    "wire",
    "finer",
    "rff",
    "bacon",
    "fourier-mfn",
    "gabor-mfn",
    "pnf",
]

PAPER = {
    "siren": "Sitzmann+ 2020",
    "hsiren": "Cai & Pan 2024",
    "wire": "Saragadam+ 2023",
    "finer": "Liu+ 2024",
    "rff": "Tancik+ 2020",
    "bacon": "Lindell+ 2022",
    "fourier-mfn": "Fathony+ 2021",
    "gabor-mfn": "Fathony+ 2021",
    "pnf": "Yang+ 2022",
}


def load_wallclock() -> dict[str, int]:
    """Parse per-basis wall-clock lines written by sweep_astronaut.sh."""
    wallclock: dict[str, int] = {}
    path = RUN_DIR / "_wallclock.txt"
    if not path.exists():
        return wallclock
    for line in path.read_text().splitlines():
        parts = line.split()
        if len(parts) >= 2:
            wallclock[parts[0]] = int(parts[1])
    return wallclock


def load_basis_metrics(basis: str) -> tuple[list[int], list[float], list[float], float, float]:
    """Return (steps, mse_per_step, psnr_per_step, final_mse, final_psnr) for one basis."""
    csv_path = RUN_DIR / basis / "loss.csv"
    steps: list[int] = []
    mse: list[float] = []
    psnr: list[float] = []
    with csv_path.open() as f:
        reader = csv.DictReader(f)
        for row in reader:
            steps.append(int(row["step"]))
            mse.append(float(row["loss"]))
            psnr.append(float(row["psnr_db"]))
    return steps, mse, psnr, mse[-1], psnr[-1]


def write_results_csv(rows: list[dict]) -> None:
    """Write the machine-readable results.csv, sorted by PSNR desc."""
    rows_sorted = sorted(rows, key=lambda r: -r["final_psnr_db"])
    out = OUT_DIR / "results.csv"
    with out.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["basis", "paper", "final_psnr_db", "final_mse", "wall_clock_seconds"])
        for r in rows_sorted:
            w.writerow(
                [
                    r["basis"],
                    r["paper"],
                    f"{r['final_psnr_db']:.2f}",
                    f"{r['final_mse']:.3e}",
                    r["wall_clock_seconds"],
                ]
            )
    print(f"wrote {out}")


def build_comparison_grid(rows: list[dict]) -> None:
    """4x3 grid: input + 9 reconstructions (skip synthetic).

    Tile size 256, gutter 12, light grey background, monospace label band
    along the bottom of each tile.
    """
    tile = 256
    gutter = 12
    label_h = 28
    cols = 3
    rows_n = 4  # 10 tiles: input + 9 bases → 12 cells, last 2 empty
    bg = (240, 240, 240)
    label_bg = (224, 224, 224)
    label_fg = (40, 40, 40)

    grid_w = cols * tile + (cols + 1) * gutter
    grid_h = rows_n * (tile + label_h) + (rows_n + 1) * gutter
    canvas = Image.new("RGB", (grid_w, grid_h), bg)
    draw = ImageDraw.Draw(canvas)

    font = None
    for cand in [
        "/System/Library/Fonts/Menlo.ttc",
        "/System/Library/Fonts/Monaco.dfont",
        "/System/Library/Fonts/Courier.dfont",
    ]:
        if Path(cand).exists():
            try:
                font = ImageFont.truetype(cand, 16)
                break
            except OSError:
                continue
    if font is None:
        font = ImageFont.load_default()

    def paste(tile_img: Image.Image, label: str, col: int, row: int) -> None:
        x = gutter + col * (tile + gutter)
        y = gutter + row * (tile + label_h + gutter)
        if tile_img.size != (tile, tile):
            tile_img = tile_img.resize((tile, tile), Image.Resampling.LANCZOS)
        canvas.paste(tile_img, (x, y))
        # Label band beneath the image
        draw.rectangle([x, y + tile, x + tile, y + tile + label_h], fill=label_bg)
        bbox = draw.textbbox((0, 0), label, font=font)
        text_w = bbox[2] - bbox[0]
        text_h = bbox[3] - bbox[1]
        draw.text(
            (x + (tile - text_w) // 2, y + tile + (label_h - text_h) // 2 - 2),
            label,
            fill=label_fg,
            font=font,
        )

    # Top-left: input (read from siren's run dir; all bases see the same input)
    input_path = RUN_DIR / "siren" / "input.png"
    paste(Image.open(input_path).convert("RGB"), "input", 0, 0)

    # Remaining cells: bases in PSNR-descending order (so the eye sweeps best→worst)
    rows_sorted = sorted(rows, key=lambda r: -r["final_psnr_db"])
    cells = [(1, 0), (2, 0), (0, 1), (1, 1), (2, 1), (0, 2), (1, 2), (2, 2), (0, 3)]
    for (col, row), r in zip(cells, rows_sorted, strict=True):
        recon = Image.open(RUN_DIR / r["basis"] / "recon_final.png").convert("RGB")
        label = f"{r['basis']} {r['final_psnr_db']:.2f} dB"
        paste(recon, label, col, row)

    out = OUT_DIR / "comparison_grid.png"
    canvas.save(out, optimize=True)
    print(f"wrote {out}")


def build_loss_curves(rows: list[dict]) -> None:
    """Overlaid MSE (log) and PSNR (linear) for all 9 bases on one figure."""
    import matplotlib

    matplotlib.use("Agg")
    # tab10 is a discrete ListedColormap whose `.colors` is a sequence of 10
    # RGB tuples. The matplotlib stubs type it as `ColorType | ArrayLike`,
    # neither of which pyright sees as Sized+Indexable; the runtime cast is
    # safe because we asked for "tab10" specifically.
    from collections.abc import Sequence
    from typing import cast

    import matplotlib.pyplot as plt
    from matplotlib.colors import ListedColormap

    cmap = plt.get_cmap("tab10")
    assert isinstance(cmap, ListedColormap)
    palette = cast(Sequence[tuple[float, float, float]], cmap.colors)

    rows_sorted = sorted(rows, key=lambda r: -r["final_psnr_db"])

    fig, (ax_mse, ax_psnr) = plt.subplots(2, 1, figsize=(10, 7.5), sharex=True, gridspec_kw={"hspace": 0.08})

    for i, r in enumerate(rows_sorted):
        steps, mse, psnr, _, _ = load_basis_metrics(r["basis"])
        color = palette[i % len(palette)]
        ax_mse.plot(steps, mse, color=color, lw=1.4, label=r["basis"])
        ax_psnr.plot(steps, psnr, color=color, lw=1.4, label=r["basis"])

    ax_mse.set_yscale("log")
    ax_mse.set_ylabel("MSE (log)")
    ax_mse.grid(True, which="both", alpha=0.25)
    ax_mse.set_title(
        "Architecture sweep on astronaut_256 — 9 bases at paper-default hparams\n"
        "hidden=128 · layers=4 · 1000 steps · seed=0 · jax-mlx-plugin",
        fontsize=12,
    )
    ax_mse.legend(loc="upper right", ncol=3, fontsize=9, framealpha=0.92)

    ax_psnr.set_ylabel("PSNR (dB)")
    ax_psnr.set_xlabel("Step")
    ax_psnr.grid(True, which="both", alpha=0.25)

    # Final-step legend in lower-right of the PSNR axis.
    final_lines = "  ".join(f"{r['basis']} {r['final_psnr_db']:.2f}" for r in rows_sorted)
    ax_psnr.annotate(
        final_lines,
        xy=(0.99, 0.02),
        xycoords="axes fraction",
        ha="right",
        va="bottom",
        fontsize=8,
        family="monospace",
        bbox={"facecolor": "white", "edgecolor": "lightgrey", "boxstyle": "round,pad=0.4"},
    )

    out = OUT_DIR / "loss_curves.svg"
    fig.savefig(out, format="svg", bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {out}")


def main() -> None:
    """Read per-run artifacts and write the four committable aggregated outputs."""
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    wallclock = load_wallclock()

    rows: list[dict] = []
    for basis in BASES:
        steps, mse, psnr, final_mse, final_psnr = load_basis_metrics(basis)
        rows.append(
            {
                "basis": basis,
                "paper": PAPER[basis],
                "final_psnr_db": final_psnr,
                "final_mse": final_mse,
                "wall_clock_seconds": wallclock.get(basis, 0),
            }
        )

    write_results_csv(rows)
    build_comparison_grid(rows)
    build_loss_curves(rows)


if __name__ == "__main__":
    main()
